### ISSUE TITLE
Wiki structure ?

### ISSUE THREAD

**Issue by kornicameister** [floreks/Qubic#12]
Think about wiki structure ?

**Comment by floreks** [comment]
Do we have to do this? Maybe using something like doxygen to generate documentation would be better?

**Comment by kornicameister** [comment]
I already have generated some Doxygen cfg file..I will put it into repository as soon as possible.

**Comment by kornicameister** [comment]
Wiki idea is now suspended...maybe in the somewhere in the future..however I want to use auto-generated [Qubic
page](http://kornicameister.github.com/Qubic/) and attach doxygen documentation there along with all examples.
Also it should be a good idea to use blogspot to describe some fancier solutions we would have provide.
