### ISSUE TITLE
Logger ?

### ISSUE THREAD

**Issue by kornicameister** [floreks/Qubic#13]
Searching for good thread-safe and fast logger
- [Patheios](http://www.pantheios.org/)
- [log4cxx](http://logging.apache.org/log4cxx/index.html)

or maybe something Qt-Based ?

**Comment by kornicameister** [comment]
http://ynonperek.com/qt-logging
in Qt ;)

**Comment by floreks** [comment]
I think this closes the logger problem ;) Qt-logger would be my choice too.

**Comment by kornicameister** [comment]
[log4cxx](http://logging.apache.org/log4cxx/index.html) seems to be quite good idea...but configuration seems to be messy...To be honest log4j is indeed easier in context of configuration...or logging itself...
